[apps.AutoDock]
product = "AutoDock"
version = "1.3.0"
minimum_macos_version = "26"
identifier = "com.ghalldev.AutoDock"
license = "MIT"
category = "public.app-category.utility"
icon = "./Sources/AppIcon.icns"
