[apps.AutoDock]
product = "AutoDock"
version = "1.3.0"
minimum_macos_version = "15"
bundle_identifier = "com.ghalldev.AutoDock"
license = "MIT"
category = "public.app-category.utility"
icon = "./Sources/AppIcon.icns"

[apps.AutoDock.extra_plist_entries]
NSAppleEventsUsageDescription = "Manage dock and menubar visibility."
LSUIElement = true
